### ISSUE TITLE
Firefox Fix

### ISSUE THREAD

**Issue by mateusz464** [leesangmin144/Expand-chatGPT-response-box#1] opened 2023-10-14 13:22 UTC
The extension does not currently work on Firefox, if you change the if statement on line 23 of content.js to be ORs then it works:

```
if (hasFlex
            && (hasP4
            || hasGap4
            || hasMAuto)) {

            divs[i].className = 'flex p-4 gap-4 text-base';
        }
```

As seen on this screenshot [here](https://i.imgur.com/xN4rSu0.png)

**Comment by leesangmin144** [comment] 2023-10-15 11:03
Hello @mateusz464,

First of all, thank you for taking the time to contribute to the project by opening an issue. Your insights are invaluable to me.

I've tested the issue on the v1.6 release and was unable to reproduce it. Furthermore, implementing the solution you've suggested appears to break the CSS styling, as illustrated in the attached image. (The version used for testing is v1.7)

- Source Code: https://i.imgur.com/fk6iAeQ.png
- Manifest: https://i.imgur.com/Try69Ce.png
- Firefox setting: https://i.imgur.com/WsSvRdj.png
- Test result: https://i.imgur.com/F7wMvpH.png

If there's something I've missed, please feel free to point it out. I suspect the issue could potentially be due to differences in monitor sizes or country-specific CSS variations. As a result, I don't intend to close the issue just yet and will continue to monitor it. If I can successfully reproduce the issue, I'll fix it promptly. Your continued assistance would be greatly appreciated.

**Comment by mateusz464** [comment] 2023-10-16 08:35
Thanks for looking into my solution.

It seems my solution only works with v1.5, after updating the code to v1.6 and trying my fix, it breaks on Firefox. The part that breaks is changing "p-4" to "flex-1", reverting that change with my fix made it work on Firefox.

If the "flex-1" is essential to the chrome build, then there could be a check if Firefox is used and use "p-4" instead.

Something like this potentially?

```
    const isFirefox = navigator.userAgent.toLowerCase().includes('firefox');

    for (let i = 0; i < divs.length; i++) {
        const divClassesStr = divs[i].classList.value;

        let hasFlex = divClassesStr.includes('flex');
        let hasP4 = isFirefox ? divClassesStr.includes('p-4') : divClassesStr.includes('flex-1');
        let hasGap4 = divClassesStr.includes('gap-4');
        let hasMAuto = divClassesStr.includes('mx-auto');

        if (isFirefox) {
            if (hasFlex && (hasP4 || hasGap4 || hasMAuto)) {
                divs[i].className = 'flex p-4 gap-4 text-base';
            }
        } else {
            if (hasFlex && hasP4 && hasGap4 && hasMAuto) {
                divs[i].className = 'flex p-4 gap-4 text-base';
            }
        }
    }
```

**Comment by mateusz464** [comment] 2023-10-16 08:41
Hi, thanks for looking into my solution and working on this project.

It seems that v1.6 has fixed the Firefox issue, and my solution only worked with v1.5. 

Also, have you looked into publishing the extension onto the Firefox Addons?

**Comment by leesangmin144** [comment] 2023-10-24 11:40
Hello @mateusz464 Sorry for the delayed response. It's good to hear that v1.6 is working as expected. 

Up until now, I have not officially supported add-on for Firefox, but I plan to extend this extension to other browsers, including a compatible version for Firefox, in the near future. 
I will mark this issue as closed. If you have any further comments, please feel free to let me know. Thank you for your interest.

**Closed as completed by leesangmin144** 2023-10-24 11:40 UTC
